name: Build and Deploy LaTeX PDF

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger from

permissions:
  contents: write       # needed so that GH actions can push to gh-pages
  pages: write          # permission to publish to pages
  id-token: write       # required for pages deployment

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: seminar.tex
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"

      - name: Prepare artifact for Pages
        run: |
          mkdir output
          cp seminar.pdf output/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  deploy:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
